New layout
bosakad/GP-Optimization pull request #3
Opened 2022-08-16 19:02 UTC by bosakad

finished layout + new readme (sorry did not see the new branch) + black + pytest + updated docs

2022-08-17 12:05 UTC, mishagli commented
I have moved the changes related to README.md to its branch, as it belongs to the Issue #2.

2022-08-17 22:03 UTC, mishagli requested changes
This notebook shouldn't be here. It rather belongs to the `/examples`.

2022-08-17 22:07 UTC, mishagli requested changes
About `/src/other/`

You are correct that you want to move some kind of utility functions to a separate folder. But it is a good practice to keep meaningful names for these as well. I'd suggest to name this folder `/utility_tools` or something like that.

The name `/other` is quite bad for several reasons. Firstly, it doesn't follow from its name what's inside. Secondly, this makes one wanting to dive into that folder because of non-needed-here curiosity :)

2022-08-17 22:22 UTC, mishagli requested changes
This file `src/timing/unaryTesting.py` shouldn't be here. What is it testing? If it is a test for your module, it should be in `/tests`. If this is a script where you played around, it should go to `/examples`.

2022-08-17 22:47 UTC, mishagli requested changes

2022-08-17 22:47 UTC, mishagli commented on setup.py
> +
I would suggest exclude those directories, where you have no packages. You packages are in `/src`. So you don't want that whatever is in `/output` and `/examples` will be written to a PATH. Particularly, this `/output` directory may have lots of different data that will probably appear there from run to run.

To do this, you should write:
```python
packages=setuptools.find_namespace_packages(exclude=["tests", "docs","examples","inputs_outputs"]),
```

2022-08-17 22:56 UTC, mishagli requested changes

2022-08-17 22:56 UTC, mishagli commented on setup.py
> +)
Please add the requirements from `requirements.txt` to `setup.py`. They should go to

```python
install_requires=[
        "cvxpy>=1.2.1",
        "cycler>=0.11.0",
        "numpy>=1.22", # and so on, please write all the packages you need here
    ],
```

Please note that I write `>=`. It is generally better to have a flexibility in packages rather that require very paricular version. You never know what changes those guys in Numy or Mosek may do so a particular version becomes deprecated or so. So we should keep upper bound open :)

2022-08-17 23:06 UTC, mishagli commented on setup.py
> +from setuptools import setup, Command
Too clumpy imports. You are importing from `setuptools` in two different lines. Surely, it should be done in one line.

So your first two lines (note the order) should be:

```python
import os
from setuptools import setup, find_packages, Command
```

2022-08-17 23:13 UTC, mishagli requested changes
Change import to be
```python
import os
from setuptools import setup, find_packages, Command
```

2022-08-18 08:30 UTC, bosakad commented
> Change import to be
> 
> ```python
> import os
> from setuptools import setup, find_packages, Command
> ```

all done and should be working:)

2022-08-18 08:31 UTC, bosakad commented
> Change import to be
> 
> ```python
> import os
> from setuptools import setup, find_packages, Command
> ```

2022-08-19 07:24 UTC, merged